/*
* generated by Xtext
*/
package de.protos.FlowOfWork.core.fow;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FoWUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.protos.FlowOfWork.core.fow.ui.internal.FoWActivator.getInstance().getInjector("de.protos.FlowOfWork.core.fow.FoW");
	}
	
}
