/*
 * generated by Xtext
 */
package de.protos.FlowOfWork.core.fow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FoWUiModule extends de.protos.FlowOfWork.core.fow.ui.AbstractFoWUiModule {
	public FoWUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
