/*
* generated by Xtext
*/
package de.protos.FlowOfWork.core.fow.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FoWAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/protos/FlowOfWork/core/fow/parser/antlr/internal/InternalFoW.tokens");
	}
}
