/*
* generated by Xtext
*/
package de.protos.FlowOfWork.core.fow.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.protos.FlowOfWork.core.fow.services.FoWGrammarAccess;

public class FoWParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FoWGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.protos.FlowOfWork.core.fow.parser.antlr.internal.InternalFoWParser createParser(XtextTokenStream stream) {
		return new de.protos.FlowOfWork.core.fow.parser.antlr.internal.InternalFoWParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public FoWGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FoWGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
