/*
 * generated by Xtext
 */
package de.protos.FlowOfWork.core.fow;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FoWRuntimeModule extends de.protos.FlowOfWork.core.fow.AbstractFoWRuntimeModule {

}
