/*******************************************************************************
 * Copyright (c) 2013 protos software gmbh (http://www.protos.de).
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * generated by Xtext
 * 
 *******************************************************************************/
package de.protos.FlowOfWork.core.fow;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FoWRuntimeModule extends de.protos.FlowOfWork.core.fow.AbstractFoWRuntimeModule {

}
