/*
* generated by Xtext
*/
package de.protos.FlowOfWork.core.fow.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractFoWJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.protos.FlowOfWork.core.fow.foW.FoWPackage.eINSTANCE);
		return result;
	}

}
