/*
* generated by Xtext
*/
package de.protos.FlowOfWork.core.fow.ui.contentassist;

import de.protos.FlowOfWork.core.fow.ui.contentassist.AbstractFoWProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FoWProposalProvider extends AbstractFoWProposalProvider {

}
