/*
* generated by Xtext
*/
package de.protos.FlowOfWork.core.fow.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FoWOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
