/*
 * generated by Xtext
 */
package de.protos.FlowOfWork.core.fow.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.protos.FlowOfWork.core.fow.ui.internal.FoWActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FoWExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FoWActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FoWActivator.getInstance().getInjector(FoWActivator.DE_PROTOS_FLOWOFWORK_CORE_FOW_FOW);
	}
	
}
